// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// Balancer V2 WeightedPool, V3 StablePool and V3 Vault events
/// <https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedPool.sol>
/// <https://github.com/balancer/balancer-v3-monorepo>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="12, 13, 14, 15, 20, 21, 30, 31, 32, 33, 34, 35, 36, 37")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// V2 WeightedPool events
        #[prost(message, tag="12")]
        SwapFeePercentage(super::SwapFeePercentage),
        #[prost(message, tag="13")]
        Paused(super::Paused),
        #[prost(message, tag="14")]
        RecoveryMode(super::RecoveryMode),
        #[prost(message, tag="15")]
        ProtocolFeePercentage(super::ProtocolFeePercentage),
        /// V3 StablePool events
        #[prost(message, tag="20")]
        AmpUpdateStarted(super::AmpUpdateStarted),
        #[prost(message, tag="21")]
        AmpUpdateStopped(super::AmpUpdateStopped),
        /// V3 Vault events
        #[prost(message, tag="30")]
        VaultSwap(super::VaultSwap),
        #[prost(message, tag="31")]
        LiquidityAdded(super::LiquidityAdded),
        #[prost(message, tag="32")]
        LiquidityRemoved(super::LiquidityRemoved),
        #[prost(message, tag="33")]
        PoolInitialized(super::PoolInitialized),
        #[prost(message, tag="34")]
        PoolRegistered(super::PoolRegistered),
        #[prost(message, tag="35")]
        PoolPaused(super::PoolPaused),
        #[prost(message, tag="36")]
        PoolRecoveryMode(super::PoolRecoveryMode),
        #[prost(message, tag="37")]
        AggregateSwapFeePercentage(super::AggregateSwapFeePercentage),
    }
}
/// / @notice Emitted when an approval is made
/// / @param owner The address of the token owner
/// / @param spender The address of the spender
/// / @param value The amount of tokens approved
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Approval {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// / @notice Emitted when tokens are transferred
/// / @param from The address sending tokens
/// / @param to The address receiving tokens
/// / @param value The amount of tokens transferred
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Transfer {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// / @notice Emitted when the swap fee percentage is changed
/// / @param swapFeePercentage The new swap fee percentage
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SwapFeePercentage {
    /// uint256
    #[prost(string, tag="1")]
    pub swap_fee_percentage: ::prost::alloc::string::String,
}
/// / @notice Emitted when the paused state is changed
/// / @param paused The new paused state
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Paused {
    /// bool
    #[prost(bool, tag="1")]
    pub paused: bool,
}
/// / @notice Emitted when the recovery mode state is changed
/// / @param enabled The new recovery mode state
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecoveryMode {
    /// bool
    #[prost(bool, tag="1")]
    pub enabled: bool,
}
/// / @notice Emitted when the protocol fee percentage cache is updated
/// / @param feeType The fee type being updated
/// / @param protocolFeePercentage The new protocol fee percentage
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProtocolFeePercentage {
    /// uint256 (indexed)
    #[prost(string, tag="1")]
    pub fee_type: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub protocol_fee_percentage: ::prost::alloc::string::String,
}
// ===== V3 StablePool Events =====

/// / @notice Emitted when an amplification parameter update is started
/// / @param startValue The starting amplification value
/// / @param endValue The ending amplification value
/// / @param startTime The timestamp when the update starts
/// / @param endTime The timestamp when the update ends
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AmpUpdateStarted {
    /// uint256
    #[prost(string, tag="1")]
    pub start_value: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub end_value: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub start_time: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub end_time: ::prost::alloc::string::String,
}
/// / @notice Emitted when an amplification parameter update is stopped
/// / @param currentValue The current amplification value
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AmpUpdateStopped {
    /// uint256
    #[prost(string, tag="1")]
    pub current_value: ::prost::alloc::string::String,
}
// ===== V3 Vault Events =====

/// / @notice Emitted when a swap is executed through the Vault
/// / @param pool The address of the pool
/// / @param tokenIn The address of the token being swapped in
/// / @param tokenOut The address of the token being swapped out
/// / @param amountIn The amount of token in
/// / @param amountOut The amount of token out
/// / @param swapFeePercentage The swap fee percentage
/// / @param swapFeeAmount The swap fee amount
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VaultSwap {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub token_in: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="3")]
    pub token_out: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub amount_in: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub amount_out: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub swap_fee_percentage: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub swap_fee_amount: ::prost::alloc::string::String,
}
/// / @notice Emitted when liquidity is added to a pool
/// / @param pool The address of the pool
/// / @param liquidityProvider The address of the liquidity provider
/// / @param kind The type of liquidity addition (enum as uint8)
/// / @param totalSupply The total supply after addition
/// / @param amountsAddedRaw The amounts of tokens added (as strings)
/// / @param swapFeeAmountsRaw The swap fee amounts (as strings)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LiquidityAdded {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub liquidity_provider: ::prost::alloc::vec::Vec<u8>,
    /// uint8 (indexed)
    #[prost(uint32, tag="3")]
    pub kind: u32,
    /// uint256
    #[prost(string, tag="4")]
    pub total_supply: ::prost::alloc::string::String,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub amounts_added_raw: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256\[\]
    #[prost(string, repeated, tag="6")]
    pub swap_fee_amounts_raw: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / @notice Emitted when liquidity is removed from a pool
/// / @param pool The address of the pool
/// / @param liquidityProvider The address of the liquidity provider
/// / @param kind The type of liquidity removal (enum as uint8)
/// / @param totalSupply The total supply after removal
/// / @param amountsRemovedRaw The amounts of tokens removed (as strings)
/// / @param swapFeeAmountsRaw The swap fee amounts (as strings)
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LiquidityRemoved {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub liquidity_provider: ::prost::alloc::vec::Vec<u8>,
    /// uint8 (indexed)
    #[prost(uint32, tag="3")]
    pub kind: u32,
    /// uint256
    #[prost(string, tag="4")]
    pub total_supply: ::prost::alloc::string::String,
    /// uint256\[\]
    #[prost(string, repeated, tag="5")]
    pub amounts_removed_raw: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256\[\]
    #[prost(string, repeated, tag="6")]
    pub swap_fee_amounts_raw: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// / @notice Emitted when a pool is initialized
/// / @param pool The address of the pool
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolInitialized {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Emitted when a pool is registered
/// / @param pool The address of the pool (indexed)
/// / @param factory The address of the factory that created the pool (indexed)
/// / @param tokenConfig Array of token configurations (token address, token type, rate provider, yield fee exempt)
/// / @param swapFeePercentage The swap fee percentage for the pool
/// / @param pauseWindowEndTime The timestamp when the pause window ends
/// / @param roleAccounts Tuple of role account addresses (pause manager, swap fee manager, pool creator)
/// / @param hooksConfig Hooks configuration flags and address
/// / @param liquidityManagement Liquidity management configuration flags
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolRegistered {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    /// TokenConfig\[\]
    #[prost(message, repeated, tag="3")]
    pub token_config: ::prost::alloc::vec::Vec<TokenConfig>,
    /// uint256
    #[prost(string, tag="4")]
    pub swap_fee_percentage: ::prost::alloc::string::String,
    /// uint32
    #[prost(string, tag="5")]
    pub pause_window_end_time: ::prost::alloc::string::String,
    /// (address, address, address)
    #[prost(message, optional, tag="6")]
    pub role_accounts: ::core::option::Option<RoleAccounts>,
    /// hooks configuration
    #[prost(message, optional, tag="7")]
    pub hooks_config: ::core::option::Option<HooksConfig>,
    /// liquidity management flags
    #[prost(message, optional, tag="8")]
    pub liquidity_management: ::core::option::Option<LiquidityManagement>,
}
/// / @notice Token configuration for a pool
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TokenConfig {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// uint8 (token type enum)
    #[prost(uint32, tag="2")]
    pub token_type: u32,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub rate_provider: ::prost::alloc::vec::Vec<u8>,
    /// bool
    #[prost(bool, tag="4")]
    pub pays_yield_fees: bool,
}
/// / @notice Role accounts for pool management
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoleAccounts {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub pause_manager: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub swap_fee_manager: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="3")]
    pub pool_creator: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Hooks configuration
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HooksConfig {
    #[prost(bool, tag="1")]
    pub enable_hook_adjusted_amounts: bool,
    #[prost(bool, tag="2")]
    pub should_call_before_initialize: bool,
    #[prost(bool, tag="3")]
    pub should_call_after_initialize: bool,
    #[prost(bool, tag="4")]
    pub should_call_compute_dynamic_swap_fee: bool,
    #[prost(bool, tag="5")]
    pub should_call_before_swap: bool,
    #[prost(bool, tag="6")]
    pub should_call_after_swap: bool,
    #[prost(bool, tag="7")]
    pub should_call_before_add_liquidity: bool,
    #[prost(bool, tag="8")]
    pub should_call_after_add_liquidity: bool,
    #[prost(bool, tag="9")]
    pub should_call_before_remove_liquidity: bool,
    #[prost(bool, tag="10")]
    pub should_call_after_remove_liquidity: bool,
    /// address
    #[prost(bytes="vec", tag="11")]
    pub hooks_address: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Liquidity management configuration
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LiquidityManagement {
    #[prost(bool, tag="1")]
    pub disable_unbalanced_liquidity: bool,
    #[prost(bool, tag="2")]
    pub enable_add_liquidity_custom: bool,
    #[prost(bool, tag="3")]
    pub enable_remove_liquidity_custom: bool,
    #[prost(bool, tag="4")]
    pub enable_donation: bool,
}
/// StorePool - minimal pool storage type
/// Primary key: pool address
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StorePool {
    /// factory address that created the pool
    #[prost(bytes="vec", tag="1")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Emitted when a pool's paused state is changed
/// / @param pool The address of the pool
/// / @param paused The new paused state
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolPaused {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// bool
    #[prost(bool, tag="2")]
    pub paused: bool,
}
/// / @notice Emitted when a pool's recovery mode state is changed
/// / @param pool The address of the pool
/// / @param enabled The new recovery mode state
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PoolRecoveryMode {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// bool
    #[prost(bool, tag="2")]
    pub enabled: bool,
}
/// / @notice Emitted when the aggregate swap fee percentage is changed
/// / @param pool The address of the pool
/// / @param aggregateSwapFeePercentage The new aggregate swap fee percentage
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AggregateSwapFeePercentage {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub aggregate_swap_fee_percentage: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
