// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// <https://github.com/bancorprotocol/contracts-solidity/blob/master/solidity/contracts/converter/types/standard-pool/StandardPoolConverter.sol>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="10")]
        Activation(super::Activation),
        #[prost(message, tag="11")]
        Conversion(super::Conversion),
        #[prost(message, tag="12")]
        ConversionFeeUpdate(super::ConversionFeeUpdate),
        #[prost(message, tag="13")]
        LiquidityAdded(super::LiquidityAdded),
        #[prost(message, tag="14")]
        LiquidityRemoved(super::LiquidityRemoved),
        #[prost(message, tag="15")]
        OwnerUpdate(super::OwnerUpdate),
        #[prost(message, tag="16")]
        TokenRateUpdate(super::TokenRateUpdate),
    }
}
/// / @notice Emitted when the converter is activated or deactivated
/// / @param converterType The converter type
/// / @param anchor The converter anchor address
/// / @param activated True if the converter was activated, false if deactivated
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Activation {
    /// log.address - the converter that emitted this event
    #[prost(bytes="vec", tag="1")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    /// uint16 (indexed)
    #[prost(uint32, tag="2")]
    pub converter_type: u32,
    /// address (indexed)
    #[prost(bytes="vec", tag="3")]
    pub anchor: ::prost::alloc::vec::Vec<u8>,
    /// bool (indexed)
    #[prost(bool, tag="4")]
    pub activated: bool,
}
/// / @notice Emitted when a conversion between two tokens occurs
/// / @param sourceToken The source token address
/// / @param targetToken The target token address
/// / @param trader The trader address
/// / @param sourceAmount The amount of source tokens
/// / @param targetAmount The amount of target tokens
/// / @param conversionFee The conversion fee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversion {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub source_token: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub target_token: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="3")]
    pub trader: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub source_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub target_amount: ::prost::alloc::string::String,
    /// int256
    #[prost(string, tag="6")]
    pub conversion_fee: ::prost::alloc::string::String,
}
/// / @notice Emitted when the conversion fee is updated
/// / @param prevFee The previous fee
/// / @param newFee The new fee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ConversionFeeUpdate {
    /// uint32
    #[prost(uint32, tag="1")]
    pub prev_fee: u32,
    /// uint32
    #[prost(uint32, tag="2")]
    pub new_fee: u32,
}
/// / @notice Emitted when liquidity is added to the pool
/// / @param provider The liquidity provider address
/// / @param reserveToken The reserve token address
/// / @param amount The amount of reserve tokens added
/// / @param newBalance The new reserve balance
/// / @param newSupply The new pool token supply
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityAdded {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub reserve_token: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub new_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub new_supply: ::prost::alloc::string::String,
}
/// / @notice Emitted when liquidity is removed from the pool
/// / @param provider The liquidity provider address
/// / @param reserveToken The reserve token address
/// / @param amount The amount of reserve tokens removed
/// / @param newBalance The new reserve balance
/// / @param newSupply The new pool token supply
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityRemoved {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub reserve_token: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub new_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub new_supply: ::prost::alloc::string::String,
}
/// / @notice Emitted when the owner is updated
/// / @param prevOwner The previous owner address
/// / @param newOwner The new owner address
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OwnerUpdate {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub prev_owner: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Emitted when the token rate is updated
/// / @param token1 The first token address
/// / @param token2 The second token address
/// / @param rateN The rate numerator
/// / @param rateD The rate denominator
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRateUpdate {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub token2: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub rate_n: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub rate_d: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
