// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub contracts: ::prost::alloc::vec::Vec<Contract>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contract {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", tag="3")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="4")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="5")]
    pub deployer: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="6")]
    pub factory: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="7")]
    pub code: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="8")]
    pub code_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="9")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="10")]
    pub call: ::core::option::Option<Call>,
    #[prost(message, optional, tag="11")]
    pub log: ::core::option::Option<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    /// Native block/log position fields
    #[prost(uint32, tag="6")]
    pub block_index: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(uint64, tag="2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="3")]
    pub end_ordinal: u64,
    /// sender
    #[prost(bytes="vec", tag="4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// recipient
    #[prost(bytes="vec", tag="5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint32, tag="9")]
    pub depth: u32,
    #[prost(uint32, tag="10")]
    pub parent_index: u32,
    #[prost(enumeration="CallType", tag="11")]
    pub call_type: i32,
    #[prost(bytes="vec", tag="13")]
    pub return_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
