// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    /// Native block/log position fields
    #[prost(uint32, tag="6")]
    pub block_index: u32,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// Pool / StableSwap (shared topic hashes — decoded from any matching contract)
        #[prost(message, tag="10")]
        TokenExchange(super::TokenExchange),
        #[prost(message, tag="11")]
        AddLiquidity(super::AddLiquidity),
        #[prost(message, tag="12")]
        RemoveLiquidity(super::RemoveLiquidity),
        #[prost(message, tag="13")]
        RemoveLiquidityOne(super::RemoveLiquidityOne),
        #[prost(message, tag="14")]
        RemoveLiquidityImbalance(super::RemoveLiquidityImbalance),
        #[prost(message, tag="15")]
        CommitNewAdmin(super::CommitNewAdmin),
        #[prost(message, tag="16")]
        NewAdmin(super::NewAdmin),
        #[prost(message, tag="17")]
        CommitNewFee(super::CommitNewFee),
        #[prost(message, tag="18")]
        NewFee(super::NewFee),
        #[prost(message, tag="19")]
        RampA(super::RampA),
        #[prost(message, tag="20")]
        StopRampA(super::StopRampA),
        /// Factory
        #[prost(message, tag="21")]
        PlainPoolDeployed(super::PlainPoolDeployed),
        #[prost(message, tag="22")]
        MetaPoolDeployed(super::MetaPoolDeployed),
        #[prost(message, tag="23")]
        BasePoolAdded(super::BasePoolAdded),
        #[prost(message, tag="24")]
        LiquidityGaugeDeployed(super::LiquidityGaugeDeployed),
        /// CryptoSwap (contract-specific: different topic hashes from Pool/StableSwap)
        #[prost(message, tag="25")]
        CryptoswapTokenExchange(super::CryptoSwapTokenExchange),
        #[prost(message, tag="26")]
        CryptoswapAddLiquidity(super::CryptoSwapAddLiquidity),
        #[prost(message, tag="27")]
        CryptoswapRemoveLiquidity(super::CryptoSwapRemoveLiquidity),
        #[prost(message, tag="28")]
        CryptoswapRemoveLiquidityOne(super::CryptoSwapRemoveLiquidityOne),
        #[prost(message, tag="29")]
        CryptoswapClaimAdminFee(super::CryptoSwapClaimAdminFee),
        #[prost(message, tag="30")]
        CryptoswapCommitNewParameters(super::CryptoSwapCommitNewParameters),
        #[prost(message, tag="31")]
        CryptoswapNewParameters(super::CryptoSwapNewParameters),
        #[prost(message, tag="32")]
        CryptoswapRampAgamma(super::CryptoSwapRampAgamma),
        #[prost(message, tag="33")]
        CryptoswapStopRampA(super::CryptoSwapStopRampA),
        /// CryptoSwapFactory
        #[prost(message, tag="34")]
        CryptoPoolDeployed(super::CryptoPoolDeployed),
        #[prost(message, tag="35")]
        CryptoswapfactoryLiquidityGaugeDeployed(super::CryptoSwapFactoryLiquidityGaugeDeployed),
        #[prost(message, tag="36")]
        CryptoswapfactoryTransferOwnership(super::CryptoSwapFactoryTransferOwnership),
        #[prost(message, tag="37")]
        CryptoswapfactoryUpdateFeeReceiver(super::CryptoSwapFactoryUpdateFeeReceiver),
        #[prost(message, tag="38")]
        CryptoswapfactoryUpdateGaugeImplementation(super::CryptoSwapFactoryUpdateGaugeImplementation),
        #[prost(message, tag="39")]
        CryptoswapfactoryUpdatePoolImplementation(super::CryptoSwapFactoryUpdatePoolImplementation),
        #[prost(message, tag="40")]
        CryptoswapfactoryUpdateTokenImplementation(super::CryptoSwapFactoryUpdateTokenImplementation),
        /// Direct pool deployment (non-factory): decoded from constructor calldata
        #[prost(message, tag="41")]
        Init(super::Init),
    }
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(uint64, tag="2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="3")]
    pub end_ordinal: u64,
    /// sender
    #[prost(bytes="vec", tag="4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// recipient
    #[prost(bytes="vec", tag="5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint32, tag="9")]
    pub depth: u32,
    #[prost(uint32, tag="10")]
    pub parent_index: u32,
    #[prost(enumeration="CallType", tag="11")]
    pub call_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenExchange {
    #[prost(bytes="vec", tag="1")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    /// int128
    #[prost(string, tag="2")]
    pub sold_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub tokens_sold: ::prost::alloc::string::String,
    /// int128
    #[prost(string, tag="4")]
    pub bought_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub tokens_bought: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub invariant: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityOne {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub coin_amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidityImbalance {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="3")]
    pub fees: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="4")]
    pub invariant: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub token_supply: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitNewAdmin {
    /// uint256
    #[prost(string, tag="1")]
    pub deadline: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="2")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewAdmin {
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitNewFee {
    /// uint256
    #[prost(string, tag="1")]
    pub deadline: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub admin_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewFee {
    /// uint256
    #[prost(string, tag="1")]
    pub fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub admin_fee: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RampA {
    /// uint256
    #[prost(string, tag="1")]
    pub old_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub new_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub initial_time: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub future_time: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopRampA {
    /// uint256
    #[prost(string, tag="1")]
    pub a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub t: ::prost::alloc::string::String,
}
/// Store messages
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolInfo {
    #[prost(bytes="vec", tag="1")]
    pub pool_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub total_liquidity: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlainPoolDeployed {
    /// call.address CREATE
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", repeated, tag="2")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// uint256
    #[prost(string, tag="3")]
    pub a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub fee: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub deployer: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaPoolDeployed {
    /// call.address CREATE
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub coin: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub base_pool: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="4")]
    pub a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub fee: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="6")]
    pub deployer: ::prost::alloc::vec::Vec<u8>,
}
/// StorePool - minimal pool storage type
/// Primary key: pool address
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorePool {
    /// array of coin addresses
    #[prost(bytes="vec", repeated, tag="1")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// factory address that created the pool
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BasePoolAdded {
    #[prost(bytes="vec", tag="1")]
    pub base_pool: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityGaugeDeployed {
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub gauge: ::prost::alloc::vec::Vec<u8>,
}
// ── CryptoSwap events (contract-specific: unique topic hashes) ────────────────

/// curvefi_cryptoswap_tokenexchange
/// CryptoSwap TokenExchange has a different topic signature to the Pool/StableSwap variant.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapTokenExchange {
    #[prost(bytes="vec", tag="1")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub sold_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub tokens_sold: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub bought_id: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub tokens_bought: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_addliquidity
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapAddLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256 (single fee, not per-coin array)
    #[prost(string, tag="3")]
    pub fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub token_supply: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_removeliquidity
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapRemoveLiquidity {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256\[3\]
    #[prost(string, repeated, tag="2")]
    pub token_amounts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// uint256
    #[prost(string, tag="3")]
    pub token_supply: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_removeliquidityone
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapRemoveLiquidityOne {
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub coin_index: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub coin_amount: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_claimadminfee
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapClaimAdminFee {
    #[prost(bytes="vec", tag="1")]
    pub admin: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub tokens: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_commitnewparameters
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapCommitNewParameters {
    /// uint256
    #[prost(string, tag="1")]
    pub deadline: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub admin_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub mid_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub out_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub fee_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub allowed_extra_profit: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub adjustment_step: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="8")]
    pub ma_half_time: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_newparameters
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapNewParameters {
    /// uint256
    #[prost(string, tag="1")]
    pub admin_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub mid_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub out_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub fee_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub allowed_extra_profit: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub adjustment_step: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub ma_half_time: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_rampagamma
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapRampAgamma {
    /// uint256
    #[prost(string, tag="1")]
    pub initial_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub future_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub initial_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub future_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub initial_time: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub future_time: ::prost::alloc::string::String,
}
/// curvefi_cryptoswap_stoprampa
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapStopRampA {
    /// uint256
    #[prost(string, tag="1")]
    pub current_a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub current_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub time: ::prost::alloc::string::String,
}
// ── CryptoSwapFactory events ──────────────────────────────────────────────────

/// curvefi_cryptoswapfactory_cryptopooldeployed
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoPoolDeployed {
    /// call.address CREATE (pool contract)
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// LP token address
    #[prost(bytes="vec", tag="2")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// \[coin0, coin1\]
    #[prost(bytes="vec", repeated, tag="3")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// uint256
    #[prost(string, tag="4")]
    pub a: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub mid_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub out_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="8")]
    pub allowed_extra_profit: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="9")]
    pub fee_gamma: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="10")]
    pub adjustment_step: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="11")]
    pub admin_fee: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="12")]
    pub ma_half_time: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="13")]
    pub initial_price: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="14")]
    pub deployer: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_liquiditygaugedeployed
/// Differs from Factory's LiquidityGaugeDeployed by including the LP token field.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryLiquidityGaugeDeployed {
    #[prost(bytes="vec", tag="1")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub gauge: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_transferownership
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryTransferOwnership {
    #[prost(bytes="vec", tag="1")]
    pub old_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_updatefeereceiver
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryUpdateFeeReceiver {
    #[prost(bytes="vec", tag="1")]
    pub old_fee_receiver: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub new_fee_receiver: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_updategaugeimplementation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryUpdateGaugeImplementation {
    #[prost(bytes="vec", tag="1")]
    pub old_gauge_implementation: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub new_gauge_implementation: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_updatepoolimplementation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryUpdatePoolImplementation {
    #[prost(bytes="vec", tag="1")]
    pub old_pool_implementation: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub new_pool_implementation: ::prost::alloc::vec::Vec<u8>,
}
/// curvefi_cryptoswapfactory_updatetokenimplementation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CryptoSwapFactoryUpdateTokenImplementation {
    #[prost(bytes="vec", tag="1")]
    pub old_token_implementation: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub new_token_implementation: ::prost::alloc::vec::Vec<u8>,
}
// ── Direct pool deployment (decoded from constructor calldata) ─────────────────

/// curvefi_pool_init
/// Decoded from direct pool deployment (non-factory) __init__ constructor calldata.
/// Captures coins, owner, pool token, and parameters for pools deployed without a factory event.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Init {
    /// deployed pool contract address
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// _owner (initial admin/owner)
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// _coins array (2–4 token addresses)
    #[prost(bytes="vec", repeated, tag="3")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// _pool_token LP token address
    #[prost(bytes="vec", tag="4")]
    pub pool_token: ::prost::alloc::vec::Vec<u8>,
    /// _A amplification coefficient (uint256)
    #[prost(string, tag="5")]
    pub a: ::prost::alloc::string::String,
    /// _fee exchange fee (uint256, scaled 1e10)
    #[prost(string, tag="6")]
    pub fee: ::prost::alloc::string::String,
    /// _admin_fee admin fee fraction (uint256, scaled 1e10)
    #[prost(string, tag="7")]
    pub admin_fee: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
