// @generated
// This file is @generated by prost-build.
/// Shared foundational DEX pool metadata. Protocol-specific initialization fields remain
/// available on the original pool-creation events and are intentionally excluded here.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    #[prost(bytes="vec", repeated, tag="1")]
    pub tokens: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
