// @generated
// This file is @generated by prost-build.
/// Unified container for normalized DEX swap events across all protocols
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexSwaps {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<DexSwap>,
    #[prost(message, repeated, tag="2")]
    pub swaps_flash: ::prost::alloc::vec::Vec<DexSwapFlash>,
}
/// A single normalized DEX swap with a clear directional input/output pair
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexSwap {
    /// transaction --
    #[prost(uint32, tag="1")]
    pub tx_index: u32,
    #[prost(bytes="vec", tag="2")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub tx_from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="4")]
    pub tx_to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub tx_nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub tx_gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub tx_gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub tx_gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub tx_value: ::prost::alloc::string::String,
    /// call (only available on chains with DetailLevel: EXTENDED) --
    #[prost(message, optional, tag="10")]
    pub call: ::core::option::Option<Call>,
    /// log --
    #[prost(uint32, tag="11")]
    pub log_index: u32,
    #[prost(uint32, tag="12")]
    pub log_block_index: u32,
    #[prost(bytes="vec", tag="13")]
    pub log_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub log_ordinal: u64,
    #[prost(bytes="vec", repeated, tag="15")]
    pub log_topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="16")]
    pub log_data: ::prost::alloc::vec::Vec<u8>,
    /// normalized swap fields --
    /// e.g. "uniswap_v2", "aerodrome"
    #[prost(string, tag="20")]
    pub protocol: ::prost::alloc::string::String,
    /// factory contract address
    #[prost(bytes="vec", tag="21")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    /// pool/exchange contract address
    #[prost(bytes="vec", tag="22")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    /// user wallet that initiated the swap
    #[prost(bytes="vec", tag="23")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    /// input token address
    #[prost(bytes="vec", tag="24")]
    pub input_contract: ::prost::alloc::vec::Vec<u8>,
    /// uint256 input token amount
    #[prost(string, tag="25")]
    pub input_amount: ::prost::alloc::string::String,
    /// output token address
    #[prost(bytes="vec", tag="26")]
    pub output_contract: ::prost::alloc::vec::Vec<u8>,
    /// uint256 output token amount
    #[prost(string, tag="27")]
    pub output_amount: ::prost::alloc::string::String,
}
/// Flash/complex swap that cannot be losslessly normalized to a single input/output pair
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexSwapFlash {
    /// transaction --
    #[prost(uint32, tag="1")]
    pub tx_index: u32,
    #[prost(bytes="vec", tag="2")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub tx_from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="4")]
    pub tx_to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub tx_nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub tx_gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub tx_gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub tx_gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub tx_value: ::prost::alloc::string::String,
    /// call (only available on chains with DetailLevel: EXTENDED) --
    #[prost(message, optional, tag="10")]
    pub call: ::core::option::Option<Call>,
    /// log --
    #[prost(uint32, tag="11")]
    pub log_index: u32,
    #[prost(uint32, tag="12")]
    pub log_block_index: u32,
    #[prost(bytes="vec", tag="13")]
    pub log_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="14")]
    pub log_ordinal: u64,
    #[prost(bytes="vec", repeated, tag="15")]
    pub log_topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="16")]
    pub log_data: ::prost::alloc::vec::Vec<u8>,
    /// raw swap data --
    #[prost(string, tag="20")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="21")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="22")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="23")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="24")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="25")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="26")]
    pub amount0_in: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="27")]
    pub amount1_in: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="28")]
    pub amount0_out: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="29")]
    pub amount1_out: ::prost::alloc::string::String,
}
/// Unified container for DEX pool initialization events across all protocols
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexPools {
    #[prost(message, repeated, tag="1")]
    pub pools: ::prost::alloc::vec::Vec<DexPool>,
}
/// A single DEX pool with a generalized array-of-coins token representation
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DexPool {
    /// pool address (primary identifier / store key)
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// e.g. "uniswap_v2", "curvefi"
    #[prost(string, tag="2")]
    pub protocol: ::prost::alloc::string::String,
    /// factory contract that created the pool
    #[prost(bytes="vec", tag="3")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    /// generalized token array (order matches on-chain indexing)
    #[prost(bytes="vec", repeated, tag="4")]
    pub coins: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// creation context
    #[prost(bytes="vec", tag="5")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="6")]
    pub log_index: u32,
    #[prost(uint64, tag="7")]
    pub log_ordinal: u64,
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(uint64, tag="2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="3")]
    pub end_ordinal: u64,
    /// sender
    #[prost(bytes="vec", tag="4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// recipient
    #[prost(bytes="vec", tag="5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint32, tag="9")]
    pub depth: u32,
    #[prost(uint32, tag="10")]
    pub parent_index: u32,
    #[prost(enumeration="CallType", tag="11")]
    pub call_type: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are not normally
    /// used directly (e.g. map_merge), but may be useful for debugging or
    /// matching purposes.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
