// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub nonce: u64,
    #[prost(string, tag="5")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub gas_limit: u64,
    #[prost(uint64, tag="7")]
    pub gas_used: u64,
    #[prost(string, tag="8")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="9")]
    pub swaps: ::prost::alloc::vec::Vec<Swap>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub input_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub input_amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="7")]
    pub output_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub output_amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub log_ordinal: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    Aerodrome = 1,
    Balancer = 2,
    Bancor = 3,
    Cow = 4,
    Curvefi = 5,
    Dodo = 6,
    KyberElastic = 7,
    Sunpump = 8,
    Traderjoe = 9,
    UniswapV1 = 10,
    UniswapV2 = 11,
    UniswapV3 = 12,
    UniswapV4 = 13,
    Woofi = 14,
}
impl Protocol {
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PROTOCOL_UNSPECIFIED",
            Self::Aerodrome => "PROTOCOL_AERODROME",
            Self::Balancer => "PROTOCOL_BALANCER",
            Self::Bancor => "PROTOCOL_BANCOR",
            Self::Cow => "PROTOCOL_COW",
            Self::Curvefi => "PROTOCOL_CURVEFI",
            Self::Dodo => "PROTOCOL_DODO",
            Self::KyberElastic => "PROTOCOL_KYBER_ELASTIC",
            Self::Sunpump => "PROTOCOL_SUNPUMP",
            Self::Traderjoe => "PROTOCOL_TRADERJOE",
            Self::UniswapV1 => "PROTOCOL_UNISWAP_V1",
            Self::UniswapV2 => "PROTOCOL_UNISWAP_V2",
            Self::UniswapV3 => "PROTOCOL_UNISWAP_V3",
            Self::UniswapV4 => "PROTOCOL_UNISWAP_V4",
            Self::Woofi => "PROTOCOL_WOOFI",
        }
    }
}
