// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    #[prost(uint32, tag="6")]
    pub block_index: u32,
    #[prost(oneof="log::Log", tags="10, 11, 12")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="10")]
        Swap(super::Swap),
        #[prost(message, tag="11")]
        SwapFee(super::SwapFee),
        #[prost(message, tag="12")]
        Initialize(super::Initialize),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag="1")]
    pub index: u32,
    #[prost(uint64, tag="2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag="3")]
    pub end_ordinal: u64,
    #[prost(bytes="vec", tag="4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag="8")]
    pub gas_limit: u64,
    #[prost(uint32, tag="9")]
    pub depth: u32,
    #[prost(uint32, tag="10")]
    pub parent_index: u32,
    #[prost(enumeration="CallType", tag="11")]
    pub call_type: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub input_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub input_amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="7")]
    pub output_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub output_amount: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapFee {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub fee: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    Aerodrome = 1,
    Balancer = 2,
    Bancor = 3,
    Cow = 4,
    Curvefi = 5,
    Dodo = 6,
    KyberElastic = 7,
    Sunpump = 8,
    Traderjoe = 9,
    UniswapV1 = 10,
    UniswapV2 = 11,
    UniswapV3 = 12,
    UniswapV4 = 13,
    Woofi = 14,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Protocol::Unspecified => "PROTOCOL_UNSPECIFIED",
            Protocol::Aerodrome => "PROTOCOL_AERODROME",
            Protocol::Balancer => "PROTOCOL_BALANCER",
            Protocol::Bancor => "PROTOCOL_BANCOR",
            Protocol::Cow => "PROTOCOL_COW",
            Protocol::Curvefi => "PROTOCOL_CURVEFI",
            Protocol::Dodo => "PROTOCOL_DODO",
            Protocol::KyberElastic => "PROTOCOL_KYBER_ELASTIC",
            Protocol::Sunpump => "PROTOCOL_SUNPUMP",
            Protocol::Traderjoe => "PROTOCOL_TRADERJOE",
            Protocol::UniswapV1 => "PROTOCOL_UNISWAP_V1",
            Protocol::UniswapV2 => "PROTOCOL_UNISWAP_V2",
            Protocol::UniswapV3 => "PROTOCOL_UNISWAP_V3",
            Protocol::UniswapV4 => "PROTOCOL_UNISWAP_V4",
            Protocol::Woofi => "PROTOCOL_WOOFI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "PROTOCOL_AERODROME" => Some(Self::Aerodrome),
            "PROTOCOL_BALANCER" => Some(Self::Balancer),
            "PROTOCOL_BANCOR" => Some(Self::Bancor),
            "PROTOCOL_COW" => Some(Self::Cow),
            "PROTOCOL_CURVEFI" => Some(Self::Curvefi),
            "PROTOCOL_DODO" => Some(Self::Dodo),
            "PROTOCOL_KYBER_ELASTIC" => Some(Self::KyberElastic),
            "PROTOCOL_SUNPUMP" => Some(Self::Sunpump),
            "PROTOCOL_TRADERJOE" => Some(Self::Traderjoe),
            "PROTOCOL_UNISWAP_V1" => Some(Self::UniswapV1),
            "PROTOCOL_UNISWAP_V2" => Some(Self::UniswapV2),
            "PROTOCOL_UNISWAP_V3" => Some(Self::UniswapV3),
            "PROTOCOL_UNISWAP_V4" => Some(Self::UniswapV4),
            "PROTOCOL_WOOFI" => Some(Self::Woofi),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
