// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="4")]
    pub nonce: u64,
    #[prost(string, tag="5")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub gas_limit: u64,
    #[prost(uint64, tag="7")]
    pub gas_used: u64,
    #[prost(string, tag="8")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="9")]
    pub swaps: ::prost::alloc::vec::Vec<Swap>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(enumeration="Protocol", tag="1")]
    pub protocol: i32,
    #[prost(bytes="vec", tag="2")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="4")]
    pub user: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="5")]
    pub input_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="6")]
    pub input_amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="7")]
    pub output_token: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag="8")]
    pub output_amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub log_ordinal: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    Unspecified = 0,
    Aerodrome = 1,
    Balancer = 2,
    Bancor = 3,
    Cow = 4,
    Curvefi = 5,
    Dodo = 6,
    KyberElastic = 7,
    Sunpump = 8,
    Traderjoe = 9,
    UniswapV1 = 10,
    UniswapV2 = 11,
    UniswapV3 = 12,
    UniswapV4 = 13,
    Woofi = 14,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Protocol::Unspecified => "PROTOCOL_UNSPECIFIED",
            Protocol::Aerodrome => "PROTOCOL_AERODROME",
            Protocol::Balancer => "PROTOCOL_BALANCER",
            Protocol::Bancor => "PROTOCOL_BANCOR",
            Protocol::Cow => "PROTOCOL_COW",
            Protocol::Curvefi => "PROTOCOL_CURVEFI",
            Protocol::Dodo => "PROTOCOL_DODO",
            Protocol::KyberElastic => "PROTOCOL_KYBER_ELASTIC",
            Protocol::Sunpump => "PROTOCOL_SUNPUMP",
            Protocol::Traderjoe => "PROTOCOL_TRADERJOE",
            Protocol::UniswapV1 => "PROTOCOL_UNISWAP_V1",
            Protocol::UniswapV2 => "PROTOCOL_UNISWAP_V2",
            Protocol::UniswapV3 => "PROTOCOL_UNISWAP_V3",
            Protocol::UniswapV4 => "PROTOCOL_UNISWAP_V4",
            Protocol::Woofi => "PROTOCOL_WOOFI",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_UNSPECIFIED" => Some(Self::Unspecified),
            "PROTOCOL_AERODROME" => Some(Self::Aerodrome),
            "PROTOCOL_BALANCER" => Some(Self::Balancer),
            "PROTOCOL_BANCOR" => Some(Self::Bancor),
            "PROTOCOL_COW" => Some(Self::Cow),
            "PROTOCOL_CURVEFI" => Some(Self::Curvefi),
            "PROTOCOL_DODO" => Some(Self::Dodo),
            "PROTOCOL_KYBER_ELASTIC" => Some(Self::KyberElastic),
            "PROTOCOL_SUNPUMP" => Some(Self::Sunpump),
            "PROTOCOL_TRADERJOE" => Some(Self::Traderjoe),
            "PROTOCOL_UNISWAP_V1" => Some(Self::UniswapV1),
            "PROTOCOL_UNISWAP_V2" => Some(Self::UniswapV2),
            "PROTOCOL_UNISWAP_V3" => Some(Self::UniswapV3),
            "PROTOCOL_UNISWAP_V4" => Some(Self::UniswapV4),
            "PROTOCOL_WOOFI" => Some(Self::Woofi),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
