// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub total_supplies: ::prost::alloc::vec::Vec<TotalSupply>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TotalSupply {
    /// token contract address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// totalSupply() -> uint256
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
