// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag = "5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag = "6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub gas_limit: u64,
    #[prost(uint64, tag = "8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag = "9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub ordinal: u64,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag = "5")]
    pub call: ::core::option::Option<Call>,
    #[prost(
        oneof = "log::Log",
        tags = "10, 11, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54, 55, 56, 60, 61, 62, 63, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120"
    )]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// ========== WETH Events ==========
        #[prost(message, tag = "10")]
        WethDeposit(super::WethDeposit),
        #[prost(message, tag = "11")]
        WethWithdrawal(super::WethWithdrawal),
        /// ========== USDC Events ==========
        #[prost(message, tag = "20")]
        UsdcMint(super::UsdcMint),
        #[prost(message, tag = "21")]
        UsdcBurn(super::UsdcBurn),
        #[prost(message, tag = "22")]
        UsdcBlacklisted(super::UsdcBlacklisted),
        #[prost(message, tag = "23")]
        UsdcBlacklisterChanged(super::UsdcBlacklisterChanged),
        #[prost(message, tag = "24")]
        UsdcMasterMinterChanged(super::UsdcMasterMinterChanged),
        #[prost(message, tag = "25")]
        UsdcMinterConfigured(super::UsdcMinterConfigured),
        #[prost(message, tag = "26")]
        UsdcMinterRemoved(super::UsdcMinterRemoved),
        #[prost(message, tag = "27")]
        UsdcOwnershipTransferred(super::UsdcOwnershipTransferred),
        #[prost(message, tag = "28")]
        UsdcPause(super::UsdcPause),
        #[prost(message, tag = "29")]
        UsdcPauserChanged(super::UsdcPauserChanged),
        #[prost(message, tag = "30")]
        UsdcRescuerChanged(super::UsdcRescuerChanged),
        #[prost(message, tag = "31")]
        UsdcUnBlacklisted(super::UsdcUnBlacklisted),
        #[prost(message, tag = "32")]
        UsdcUnpause(super::UsdcUnpause),
        #[prost(message, tag = "33")]
        UsdcAuthorizationCanceled(super::UsdcAuthorizationCanceled),
        #[prost(message, tag = "34")]
        UsdcAuthorizationUsed(super::UsdcAuthorizationUsed),
        /// ========== USDT Events ==========
        #[prost(message, tag = "40")]
        UsdtIssue(super::UsdtIssue),
        #[prost(message, tag = "41")]
        UsdtRedeem(super::UsdtRedeem),
        #[prost(message, tag = "42")]
        UsdtDeprecate(super::UsdtDeprecate),
        #[prost(message, tag = "43")]
        UsdtParams(super::UsdtParams),
        #[prost(message, tag = "44")]
        UsdtDestroyedBlackFunds(super::UsdtDestroyedBlackFunds),
        #[prost(message, tag = "45")]
        UsdtAddedBlackList(super::UsdtAddedBlackList),
        #[prost(message, tag = "46")]
        UsdtRemovedBlackList(super::UsdtRemovedBlackList),
        #[prost(message, tag = "47")]
        UsdtPause(super::UsdtPause),
        #[prost(message, tag = "48")]
        UsdtUnpause(super::UsdtUnpause),
        /// ========== WBTC Events ==========
        #[prost(message, tag = "50")]
        WbtcMint(super::WbtcMint),
        #[prost(message, tag = "51")]
        WbtcBurn(super::WbtcBurn),
        #[prost(message, tag = "52")]
        WbtcMintFinished(super::WbtcMintFinished),
        #[prost(message, tag = "53")]
        WbtcOwnershipRenounced(super::WbtcOwnershipRenounced),
        #[prost(message, tag = "54")]
        WbtcOwnershipTransferred(super::WbtcOwnershipTransferred),
        #[prost(message, tag = "55")]
        WbtcPause(super::WbtcPause),
        #[prost(message, tag = "56")]
        WbtcUnpause(super::WbtcUnpause),
        /// ========== SAI Events ==========
        #[prost(message, tag = "60")]
        SaiMint(super::SaiMint),
        #[prost(message, tag = "61")]
        SaiBurn(super::SaiBurn),
        #[prost(message, tag = "62")]
        SaiLogSetAuthority(super::SaiLogSetAuthority),
        #[prost(message, tag = "63")]
        SaiLogSetOwner(super::SaiLogSetOwner),
        /// ========== stETH Events ==========
        #[prost(message, tag = "100")]
        StethSubmitted(super::StethSubmitted),
        #[prost(message, tag = "101")]
        StethUnbuffered(super::StethUnbuffered),
        #[prost(message, tag = "102")]
        StethTokenRebased(super::StethTokenRebased),
        #[prost(message, tag = "103")]
        StethTransferShares(super::StethTransferShares),
        #[prost(message, tag = "104")]
        StethSharesBurnt(super::StethSharesBurnt),
        #[prost(message, tag = "105")]
        StethExternalSharesMinted(super::StethExternalSharesMinted),
        #[prost(message, tag = "106")]
        StethExternalSharesBurnt(super::StethExternalSharesBurnt),
        #[prost(message, tag = "107")]
        StethExternalEtherTransferredToBuffer(
            super::StethExternalEtherTransferredToBuffer,
        ),
        #[prost(message, tag = "108")]
        StethExternalBadDebtInternalized(super::StethExternalBadDebtInternalized),
        #[prost(message, tag = "109")]
        StethMaxExternalRatioBpSet(super::StethMaxExternalRatioBpSet),
        #[prost(message, tag = "110")]
        StethClValidatorsUpdated(super::StethClValidatorsUpdated),
        #[prost(message, tag = "111")]
        StethDepositedValidatorsChanged(super::StethDepositedValidatorsChanged),
        #[prost(message, tag = "112")]
        StethEthDistributed(super::StethEthDistributed),
        #[prost(message, tag = "113")]
        StethInternalShareRateUpdated(super::StethInternalShareRateUpdated),
        #[prost(message, tag = "114")]
        StethStakingPaused(super::StethStakingPaused),
        #[prost(message, tag = "115")]
        StethStakingResumed(super::StethStakingResumed),
        #[prost(message, tag = "116")]
        StethStakingLimitSet(super::StethStakingLimitSet),
        #[prost(message, tag = "117")]
        StethStakingLimitRemoved(super::StethStakingLimitRemoved),
        #[prost(message, tag = "118")]
        StethElRewardsReceived(super::StethElRewardsReceived),
        #[prost(message, tag = "119")]
        StethWithdrawalsReceived(super::StethWithdrawalsReceived),
        #[prost(message, tag = "120")]
        StethLidoLocatorSet(super::StethLidoLocatorSet),
    }
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    /// Address that made the call
    #[prost(bytes = "vec", tag = "1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// Index of the call within the transaction
    #[prost(uint32, tag = "2")]
    pub index: u32,
    /// Depth of the call in the call tree (0 = root)
    #[prost(uint32, tag = "3")]
    pub depth: u32,
    #[prost(enumeration = "CallType", tag = "4")]
    pub call_type: i32,
}
/// event Deposit(address indexed dst, uint256 wad)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WethDeposit {
    #[prost(bytes = "vec", tag = "1")]
    pub dst: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
/// event Withdrawal(address indexed src, uint256 wad)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WethWithdrawal {
    #[prost(bytes = "vec", tag = "1")]
    pub src: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
/// event Mint(address indexed minter, address indexed to, uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcMint {
    #[prost(bytes = "vec", tag = "1")]
    pub minter: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
/// event Burn(address indexed burner, uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcBurn {
    #[prost(bytes = "vec", tag = "1")]
    pub burner: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
/// event Blacklisted(address indexed _account)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcBlacklisted {
    #[prost(bytes = "vec", tag = "1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
}
/// event BlacklisterChanged(address indexed newBlacklister)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcBlacklisterChanged {
    #[prost(bytes = "vec", tag = "1")]
    pub new_blacklister: ::prost::alloc::vec::Vec<u8>,
}
/// event MasterMinterChanged(address indexed newMasterMinter)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcMasterMinterChanged {
    #[prost(bytes = "vec", tag = "1")]
    pub new_master_minter: ::prost::alloc::vec::Vec<u8>,
}
/// event MinterConfigured(address indexed minter, uint256 minterAllowedAmount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcMinterConfigured {
    #[prost(bytes = "vec", tag = "1")]
    pub minter: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub minter_allowed_amount: ::prost::alloc::string::String,
}
/// event MinterRemoved(address indexed oldMinter)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcMinterRemoved {
    #[prost(bytes = "vec", tag = "1")]
    pub old_minter: ::prost::alloc::vec::Vec<u8>,
}
/// event OwnershipTransferred(address previousOwner, address newOwner)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcOwnershipTransferred {
    #[prost(bytes = "vec", tag = "1")]
    pub previous_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
/// event Pause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UsdcPause {}
/// event PauserChanged(address indexed newAddress)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcPauserChanged {
    #[prost(bytes = "vec", tag = "1")]
    pub new_address: ::prost::alloc::vec::Vec<u8>,
}
/// event RescuerChanged(address indexed newRescuer)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcRescuerChanged {
    #[prost(bytes = "vec", tag = "1")]
    pub new_rescuer: ::prost::alloc::vec::Vec<u8>,
}
/// event UnBlacklisted(address indexed _account)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcUnBlacklisted {
    #[prost(bytes = "vec", tag = "1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
}
/// event Unpause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UsdcUnpause {}
/// event AuthorizationCanceled(address indexed authorizer, bytes32 indexed nonce)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcAuthorizationCanceled {
    #[prost(bytes = "vec", tag = "1")]
    pub authorizer: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes = "vec", tag = "2")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// event AuthorizationUsed(address indexed authorizer, bytes32 indexed nonce)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdcAuthorizationUsed {
    #[prost(bytes = "vec", tag = "1")]
    pub authorizer: ::prost::alloc::vec::Vec<u8>,
    /// bytes32
    #[prost(bytes = "vec", tag = "2")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
}
/// event Issue(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtIssue {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event Redeem(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtRedeem {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event Deprecate(address newAddress)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtDeprecate {
    #[prost(bytes = "vec", tag = "1")]
    pub new_address: ::prost::alloc::vec::Vec<u8>,
}
/// event Params(uint256 feeBasisPoints, uint256 maxFee)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtParams {
    /// uint256
    #[prost(string, tag = "1")]
    pub fee_basis_points: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub max_fee: ::prost::alloc::string::String,
}
/// event DestroyedBlackFunds(address _blackListedUser, uint256 _balance)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtDestroyedBlackFunds {
    #[prost(bytes = "vec", tag = "1")]
    pub black_listed_user: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub balance: ::prost::alloc::string::String,
}
/// event AddedBlackList(address _user)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtAddedBlackList {
    #[prost(bytes = "vec", tag = "1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
}
/// event RemovedBlackList(address _user)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsdtRemovedBlackList {
    #[prost(bytes = "vec", tag = "1")]
    pub user: ::prost::alloc::vec::Vec<u8>,
}
/// event Pause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UsdtPause {}
/// event Unpause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UsdtUnpause {}
/// event Mint(address indexed to, uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WbtcMint {
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
}
/// event Burn(address indexed burner, uint256 value)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WbtcBurn {
    #[prost(bytes = "vec", tag = "1")]
    pub burner: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// event MintFinished()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WbtcMintFinished {}
/// event OwnershipRenounced(address indexed previousOwner)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WbtcOwnershipRenounced {
    #[prost(bytes = "vec", tag = "1")]
    pub previous_owner: ::prost::alloc::vec::Vec<u8>,
}
/// event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WbtcOwnershipTransferred {
    #[prost(bytes = "vec", tag = "1")]
    pub previous_owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub new_owner: ::prost::alloc::vec::Vec<u8>,
}
/// event Pause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WbtcPause {}
/// event Unpause()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct WbtcUnpause {}
/// event Mint(address indexed guy, uint256 wad)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaiMint {
    #[prost(bytes = "vec", tag = "1")]
    pub guy: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
/// event Burn(address indexed guy, uint256 wad)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaiBurn {
    #[prost(bytes = "vec", tag = "1")]
    pub guy: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
/// event LogSetAuthority(address indexed authority)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaiLogSetAuthority {
    #[prost(bytes = "vec", tag = "1")]
    pub authority: ::prost::alloc::vec::Vec<u8>,
}
/// event LogSetOwner(address indexed owner)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SaiLogSetOwner {
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
/// event Submitted(address indexed sender, uint256 amount, address referral)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethSubmitted {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub referral: ::prost::alloc::vec::Vec<u8>,
}
/// event Unbuffered(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethUnbuffered {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event TokenRebased(uint256 indexed reportTimestamp, uint256 timeElapsed, uint256 preTotalShares,
///                     uint256 preTotalEther, uint256 postTotalShares, uint256 postTotalEther, uint256 sharesMintedAsFees)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethTokenRebased {
    /// uint256
    #[prost(string, tag = "1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub time_elapsed: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub pre_total_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub pre_total_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "5")]
    pub post_total_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "6")]
    pub post_total_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "7")]
    pub shares_minted_as_fees: ::prost::alloc::string::String,
}
/// event TransferShares(address indexed from, address indexed to, uint256 sharesValue)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethTransferShares {
    #[prost(bytes = "vec", tag = "1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "3")]
    pub shares_value: ::prost::alloc::string::String,
}
/// event SharesBurnt(address indexed account, uint256 preRebaseTokenAmount, uint256 postRebaseTokenAmount, uint256 sharesAmount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethSharesBurnt {
    #[prost(bytes = "vec", tag = "1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub pre_rebase_token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub post_rebase_token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub shares_amount: ::prost::alloc::string::String,
}
/// event ExternalSharesMinted(address indexed recipient, uint256 amountOfShares)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethExternalSharesMinted {
    #[prost(bytes = "vec", tag = "1")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub amount_of_shares: ::prost::alloc::string::String,
}
/// event ExternalSharesBurnt(uint256 amountOfShares)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethExternalSharesBurnt {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount_of_shares: ::prost::alloc::string::String,
}
/// event ExternalEtherTransferredToBuffer(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethExternalEtherTransferredToBuffer {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event ExternalBadDebtInternalized(uint256 amountOfShares)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethExternalBadDebtInternalized {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount_of_shares: ::prost::alloc::string::String,
}
/// event MaxExternalRatioBPSet(uint256 maxExternalRatioBP)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethMaxExternalRatioBpSet {
    /// uint256
    #[prost(string, tag = "1")]
    pub max_external_ratio_bp: ::prost::alloc::string::String,
}
/// event CLValidatorsUpdated(uint256 indexed reportTimestamp, uint256 preCLValidators, uint256 postCLValidators)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethClValidatorsUpdated {
    /// uint256
    #[prost(string, tag = "1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub pre_cl_validators: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub post_cl_validators: ::prost::alloc::string::String,
}
/// event DepositedValidatorsChanged(uint256 depositedValidators)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethDepositedValidatorsChanged {
    /// uint256
    #[prost(string, tag = "1")]
    pub deposited_validators: ::prost::alloc::string::String,
}
/// event ETHDistributed(uint256 indexed reportTimestamp, uint256 preCLBalance, uint256 postCLBalance,
///                       uint256 withdrawalsWithdrawn, uint256 executionLayerRewardsWithdrawn, uint256 postBufferedEther)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethEthDistributed {
    /// uint256
    #[prost(string, tag = "1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub pre_cl_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub post_cl_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub withdrawals_withdrawn: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "5")]
    pub execution_layer_rewards_withdrawn: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "6")]
    pub post_buffered_ether: ::prost::alloc::string::String,
}
/// event InternalShareRateUpdated(uint256 indexed reportTimestamp, uint256 postInternalShares, uint256 postInternalEther, uint256 sharesMintedAsFees)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethInternalShareRateUpdated {
    /// uint256
    #[prost(string, tag = "1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub post_internal_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub post_internal_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub shares_minted_as_fees: ::prost::alloc::string::String,
}
/// event StakingPaused()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StethStakingPaused {}
/// event StakingResumed()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StethStakingResumed {}
/// event StakingLimitSet(uint256 maxStakeLimit, uint256 stakeLimitIncreasePerBlock)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethStakingLimitSet {
    /// uint256
    #[prost(string, tag = "1")]
    pub max_stake_limit: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "2")]
    pub stake_limit_increase_per_block: ::prost::alloc::string::String,
}
/// event StakingLimitRemoved()
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StethStakingLimitRemoved {}
/// event ELRewardsReceived(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethElRewardsReceived {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event WithdrawalsReceived(uint256 amount)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethWithdrawalsReceived {
    /// uint256
    #[prost(string, tag = "1")]
    pub amount: ::prost::alloc::string::String,
}
/// event LidoLocatorSet(address lidoLocator)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StethLidoLocatorSet {
    #[prost(bytes = "vec", tag = "1")]
    pub lido_locator: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CALL_TYPE_UNSPECIFIED",
            Self::Call => "CALL_TYPE_CALL",
            Self::Callcode => "CALL_TYPE_CALLCODE",
            Self::Delegate => "CALL_TYPE_DELEGATE",
            Self::Static => "CALL_TYPE_STATIC",
            Self::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
