// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag = "5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag = "6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub gas_limit: u64,
    #[prost(uint64, tag = "8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag = "9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub ordinal: u64,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag = "5")]
    pub call: ::core::option::Option<Call>,
    #[prost(oneof = "log::Log", tags = "10, 11, 12, 13")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// ERC-20 events
        #[prost(message, tag = "10")]
        Transfer(super::Transfer),
        #[prost(message, tag = "11")]
        Approval(super::Approval),
        /// WETH events
        #[prost(message, tag = "12")]
        Deposit(super::Deposit),
        #[prost(message, tag = "13")]
        Withdrawal(super::Withdrawal),
    }
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    /// Address that made the call
    #[prost(bytes = "vec", tag = "1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// Index of the call within the transaction
    #[prost(uint32, tag = "2")]
    pub index: u32,
    /// Depth of the call in the call tree (0 = root)
    #[prost(uint32, tag = "3")]
    pub depth: u32,
    #[prost(enumeration = "CallType", tag = "4")]
    pub call_type: i32,
}
/// ERC-20 events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(bytes = "vec", tag = "1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "3")]
    pub amount: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approval {
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "3")]
    pub value: ::prost::alloc::string::String,
}
/// WETH events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(bytes = "vec", tag = "1")]
    pub dst: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Withdrawal {
    #[prost(bytes = "vec", tag = "1")]
    pub src: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub wad: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CALL_TYPE_UNSPECIFIED",
            Self::Call => "CALL_TYPE_CALL",
            Self::Callcode => "CALL_TYPE_CALLCODE",
            Self::Delegate => "CALL_TYPE_DELEGATE",
            Self::Static => "CALL_TYPE_STATIC",
            Self::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
