// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/pool-weighted/contracts/WeightedPool.sol
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        #[prost(message, tag="10")]
        Approval(super::Approval),
        #[prost(message, tag="11")]
        Transfer(super::Transfer),
        #[prost(message, tag="12")]
        SwapFeePercentageChanged(super::SwapFeePercentageChanged),
        #[prost(message, tag="13")]
        PausedStateChanged(super::PausedStateChanged),
        #[prost(message, tag="14")]
        RecoveryModeStateChanged(super::RecoveryModeStateChanged),
        #[prost(message, tag="15")]
        ProtocolFeePercentageCacheUpdated(super::ProtocolFeePercentageCacheUpdated),
    }
}
/// @notice Emitted when an approval is made
/// @param owner The address of the token owner
/// @param spender The address of the spender
/// @param value The amount of tokens approved
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approval {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// @notice Emitted when tokens are transferred
/// @param from The address sending tokens
/// @param to The address receiving tokens
/// @param value The amount of tokens transferred
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// @notice Emitted when the swap fee percentage is changed
/// @param swapFeePercentage The new swap fee percentage
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapFeePercentageChanged {
    /// uint256
    #[prost(string, tag="1")]
    pub swap_fee_percentage: ::prost::alloc::string::String,
}
/// @notice Emitted when the paused state is changed
/// @param paused The new paused state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PausedStateChanged {
    /// bool
    #[prost(bool, tag="1")]
    pub paused: bool,
}
/// @notice Emitted when the recovery mode state is changed
/// @param enabled The new recovery mode state
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecoveryModeStateChanged {
    /// bool
    #[prost(bool, tag="1")]
    pub enabled: bool,
}
/// @notice Emitted when the protocol fee percentage cache is updated
/// @param feeType The fee type being updated
/// @param protocolFeePercentage The new protocol fee percentage
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolFeePercentageCacheUpdated {
    /// uint256 (indexed)
    #[prost(string, tag="1")]
    pub fee_type: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub protocol_fee_percentage: ::prost::alloc::string::String,
}
