// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub contract_creations: ::prost::alloc::vec::Vec<ContractCreation>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContractCreation {
    /// block
    #[prost(message, optional, tag = "1")]
    pub block_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub block_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub block_number: u64,
    #[prost(string, tag = "4")]
    pub block_date: ::prost::alloc::string::String,
    /// transaction
    #[prost(string, tag = "5")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag = "6")]
    pub transaction_index: u32,
    /// contract creation
    #[prost(uint64, tag = "7")]
    pub ordinal: u64,
    #[prost(string, tag = "8")]
    pub address: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub deployer: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "12")]
    pub factory: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "13")]
    pub code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "14")]
    pub code_hash: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "15")]
    pub input: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
