// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub supplies: ::prost::alloc::vec::Vec<Supply>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Supply {
    /// token contract address
    #[prost(bytes="vec", tag="1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    /// totalSupply() -> uint256
    #[prost(string, tag="2")]
    pub total_supply: ::prost::alloc::string::String,
    /// maxSupply() or cap() -> uint256
    #[prost(string, optional, tag="3")]
    pub max_supply: ::core::option::Option<::prost::alloc::string::String>,
}
// @@protoc_insertion_point(module)
