// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag = "5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag = "6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub gas_limit: u64,
    #[prost(uint64, tag = "8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag = "9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// KyberSwap Elastic Pool and Factory events
/// <https://docs.kyberswap.com/liquidity-solutions/kyberswap-elastic>
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub ordinal: u64,
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub call: ::core::option::Option<Call>,
    /// Native block/log position fields
    #[prost(uint32, tag = "6")]
    pub block_index: u32,
    #[prost(uint32, tag = "7")]
    pub index: u32,
    #[prost(oneof = "log::Log", tags = "10, 11, 12, 13, 14, 15, 20")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// Pool events
        #[prost(message, tag = "10")]
        Swap(super::Swap),
        #[prost(message, tag = "11")]
        Mint(super::Mint),
        #[prost(message, tag = "12")]
        Burn(super::Burn),
        #[prost(message, tag = "13")]
        BurnRTokens(super::BurnRTokens),
        #[prost(message, tag = "14")]
        Flash(super::Flash),
        #[prost(message, tag = "15")]
        Initialize(super::Initialize),
        /// Factory events
        #[prost(message, tag = "20")]
        PoolCreated(super::PoolCreated),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(uint32, tag = "1")]
    pub index: u32,
    #[prost(uint64, tag = "2")]
    pub begin_ordinal: u64,
    #[prost(uint64, tag = "3")]
    pub end_ordinal: u64,
    /// sender
    #[prost(bytes = "vec", tag = "4")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// recipient
    #[prost(bytes = "vec", tag = "5")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "6")]
    pub value: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub gas_consumed: u64,
    #[prost(uint64, tag = "8")]
    pub gas_limit: u64,
    #[prost(uint32, tag = "9")]
    pub depth: u32,
    #[prost(uint32, tag = "10")]
    pub parent_index: u32,
    #[prost(enumeration = "CallType", tag = "11")]
    pub call_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorePool {
    #[prost(bytes = "vec", tag = "1")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub swap_fee_units: u32,
    #[prost(int32, tag = "5")]
    pub tick_distance: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PoolCreated {
    #[prost(bytes = "vec", tag = "1")]
    pub token0: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub token1: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub swap_fee_units: u32,
    #[prost(int32, tag = "4")]
    pub tick_distance: i32,
    /// STORE primary key
    #[prost(bytes = "vec", tag = "5")]
    pub pool: ::prost::alloc::vec::Vec<u8>,
}
/// Uses signed int256 for delta quantities (positive = received, negative = paid)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    /// int256
    #[prost(string, tag = "3")]
    pub delta_qty0: ::prost::alloc::string::String,
    /// int256
    #[prost(string, tag = "4")]
    pub delta_qty1: ::prost::alloc::string::String,
    /// uint160
    #[prost(string, tag = "5")]
    pub sqrt_p: ::prost::alloc::string::String,
    /// uint128
    #[prost(string, tag = "6")]
    pub liquidity: ::prost::alloc::string::String,
    /// int24
    #[prost(int32, tag = "7")]
    pub current_tick: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mint {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub tick_lower: i32,
    #[prost(int32, tag = "4")]
    pub tick_upper: i32,
    /// uint128
    #[prost(string, tag = "5")]
    pub qty: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "6")]
    pub qty0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "7")]
    pub qty1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Burn {
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "2")]
    pub tick_lower: i32,
    #[prost(int32, tag = "3")]
    pub tick_upper: i32,
    /// uint128
    #[prost(string, tag = "4")]
    pub qty: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "5")]
    pub qty0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "6")]
    pub qty1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BurnRTokens {
    #[prost(bytes = "vec", tag = "1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "2")]
    pub qty: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "3")]
    pub qty0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub qty1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flash {
    #[prost(bytes = "vec", tag = "1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag = "3")]
    pub qty0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "4")]
    pub qty1: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "5")]
    pub paid0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag = "6")]
    pub paid1: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    /// uint160
    #[prost(string, tag = "1")]
    pub sqrt_p: ::prost::alloc::string::String,
    /// int24
    #[prost(int32, tag = "2")]
    pub tick: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CALL_TYPE_UNSPECIFIED",
            Self::Call => "CALL_TYPE_CALL",
            Self::Callcode => "CALL_TYPE_CALLCODE",
            Self::Delegate => "CALL_TYPE_DELEGATE",
            Self::Static => "CALL_TYPE_STATIC",
            Self::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
