// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// ERC-20 standard events (stETH is an ERC-20 rebasing token)
        #[prost(message, tag="10")]
        Transfer(super::Transfer),
        #[prost(message, tag="11")]
        Approval(super::Approval),
        /// Staking events
        #[prost(message, tag="12")]
        Submitted(super::Submitted),
        #[prost(message, tag="13")]
        Unbuffered(super::Unbuffered),
        /// Rebase events
        #[prost(message, tag="14")]
        TokenRebased(super::TokenRebased),
        #[prost(message, tag="15")]
        TransferShares(super::TransferShares),
        #[prost(message, tag="16")]
        SharesBurnt(super::SharesBurnt),
        /// External shares events (Lido V3 stVaults)
        #[prost(message, tag="17")]
        ExternalSharesMinted(super::ExternalSharesMinted),
        #[prost(message, tag="18")]
        ExternalSharesBurnt(super::ExternalSharesBurnt),
        #[prost(message, tag="19")]
        ExternalEtherTransferredToBuffer(super::ExternalEtherTransferredToBuffer),
        #[prost(message, tag="20")]
        ExternalBadDebtInternalized(super::ExternalBadDebtInternalized),
        #[prost(message, tag="21")]
        MaxExternalRatioBpSet(super::MaxExternalRatioBpSet),
        /// Validator/CL events
        #[prost(message, tag="22")]
        ClValidatorsUpdated(super::ClValidatorsUpdated),
        #[prost(message, tag="23")]
        DepositedValidatorsChanged(super::DepositedValidatorsChanged),
        #[prost(message, tag="24")]
        EthDistributed(super::EthDistributed),
        #[prost(message, tag="25")]
        InternalShareRateUpdated(super::InternalShareRateUpdated),
        /// Protocol control events
        #[prost(message, tag="26")]
        StakingPaused(super::StakingPaused),
        #[prost(message, tag="27")]
        StakingResumed(super::StakingResumed),
        #[prost(message, tag="28")]
        StakingLimitSet(super::StakingLimitSet),
        #[prost(message, tag="29")]
        StakingLimitRemoved(super::StakingLimitRemoved),
        /// EL/Withdrawal events
        #[prost(message, tag="30")]
        ElRewardsReceived(super::ElRewardsReceived),
        #[prost(message, tag="31")]
        WithdrawalsReceived(super::WithdrawalsReceived),
        /// Locator event
        #[prost(message, tag="32")]
        LidoLocatorSet(super::LidoLocatorSet),
    }
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    /// Address that made the call
    #[prost(bytes="vec", tag="1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    /// Index of the call within the transaction
    #[prost(uint32, tag="2")]
    pub index: u32,
    /// Depth of the call in the call tree (0 = root)
    #[prost(uint32, tag="3")]
    pub depth: u32,
    #[prost(enumeration="CallType", tag="4")]
    pub call_type: i32,
}
// ============================================
// ERC-20 Standard Events
// ============================================

/// Transfer event (ERC-20)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount: ::prost::alloc::string::String,
}
/// Approval event (ERC-20)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approval {
    #[prost(bytes="vec", tag="1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
// ============================================
// Staking Events
// ============================================

/// Submitted - Records a deposit made by a user
/// event Submitted(address indexed sender, uint256 amount, address referral)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Submitted {
    #[prost(bytes="vec", tag="1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub amount: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub referral: ::prost::alloc::vec::Vec<u8>,
}
/// Unbuffered - The amount of ether was sent to the deposit_contract.deposit function
/// event Unbuffered(uint256 amount)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unbuffered {
    /// uint256
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
}
// ============================================
// Rebase Events
// ============================================

/// TokenRebased - Emitted when the token is rebased (an accounting oracle report is delivered)
/// event TokenRebased(uint256 indexed reportTimestamp, uint256 timeElapsed, uint256 preTotalShares, 
///                     uint256 preTotalEther, uint256 postTotalShares, uint256 postTotalEther, uint256 sharesMintedAsFees)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRebased {
    /// uint256
    #[prost(string, tag="1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub time_elapsed: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub pre_total_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub pre_total_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub post_total_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub post_total_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="7")]
    pub shares_minted_as_fees: ::prost::alloc::string::String,
}
/// TransferShares - Emitted when shares are transferred
/// event TransferShares(address indexed from, address indexed to, uint256 sharesValue)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransferShares {
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub shares_value: ::prost::alloc::string::String,
}
/// SharesBurnt - Emitted when shares are burned
/// event SharesBurnt(address indexed account, uint256 preRebaseTokenAmount, uint256 postRebaseTokenAmount, uint256 sharesAmount)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SharesBurnt {
    #[prost(bytes="vec", tag="1")]
    pub account: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub pre_rebase_token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub post_rebase_token_amount: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub shares_amount: ::prost::alloc::string::String,
}
// ============================================
// External Shares Events (Lido V3 stVaults)
// ============================================

/// ExternalSharesMinted - External shares minted for recipient
/// event ExternalSharesMinted(address indexed recipient, uint256 amountOfShares)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalSharesMinted {
    #[prost(bytes="vec", tag="1")]
    pub recipient: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="2")]
    pub amount_of_shares: ::prost::alloc::string::String,
}
/// ExternalSharesBurnt - External shares burned
/// event ExternalSharesBurnt(uint256 amountOfShares)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalSharesBurnt {
    /// uint256
    #[prost(string, tag="1")]
    pub amount_of_shares: ::prost::alloc::string::String,
    /// call.caller (not in event log)
    #[prost(bytes="vec", tag="2")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
}
/// ExternalEtherTransferredToBuffer - External ether transferred to buffer
/// event ExternalEtherTransferredToBuffer(uint256 amount)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalEtherTransferredToBuffer {
    /// uint256
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
}
/// ExternalBadDebtInternalized - Bad debt internalized
/// event ExternalBadDebtInternalized(uint256 amountOfShares)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExternalBadDebtInternalized {
    /// uint256
    #[prost(string, tag="1")]
    pub amount_of_shares: ::prost::alloc::string::String,
}
/// MaxExternalRatioBPSet - Maximum ratio of external shares to total shares in basis points set
/// event MaxExternalRatioBPSet(uint256 maxExternalRatioBP)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MaxExternalRatioBpSet {
    /// uint256
    #[prost(string, tag="1")]
    pub max_external_ratio_bp: ::prost::alloc::string::String,
}
// ============================================
// Validator/CL Events
// ============================================

/// CLValidatorsUpdated - Emitted when validators number delivered by the oracle
/// event CLValidatorsUpdated(uint256 indexed reportTimestamp, uint256 preCLValidators, uint256 postCLValidators)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClValidatorsUpdated {
    /// uint256
    #[prost(string, tag="1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub pre_cl_validators: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub post_cl_validators: ::prost::alloc::string::String,
}
/// DepositedValidatorsChanged - Emitted when depositedValidators value is changed
/// event DepositedValidatorsChanged(uint256 depositedValidators)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositedValidatorsChanged {
    /// uint256
    #[prost(string, tag="1")]
    pub deposited_validators: ::prost::alloc::string::String,
}
/// ETHDistributed - Emitted when oracle accounting report processed
/// event ETHDistributed(uint256 indexed reportTimestamp, uint256 preCLBalance, uint256 postCLBalance,
///                       uint256 withdrawalsWithdrawn, uint256 executionLayerRewardsWithdrawn, uint256 postBufferedEther)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EthDistributed {
    /// uint256
    #[prost(string, tag="1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256 (actually preCLBalance + deposits for compatibility)
    #[prost(string, tag="2")]
    pub pre_cl_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub post_cl_balance: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub withdrawals_withdrawn: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="5")]
    pub execution_layer_rewards_withdrawn: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="6")]
    pub post_buffered_ether: ::prost::alloc::string::String,
}
/// InternalShareRateUpdated - Internal share rate updated
/// event InternalShareRateUpdated(uint256 indexed reportTimestamp, uint256 postInternalShares, uint256 postInternalEther, uint256 sharesMintedAsFees)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InternalShareRateUpdated {
    /// uint256
    #[prost(string, tag="1")]
    pub report_timestamp: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub post_internal_shares: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="3")]
    pub post_internal_ether: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub shares_minted_as_fees: ::prost::alloc::string::String,
}
// ============================================
// Protocol Control Events
// ============================================

/// StakingPaused - Staking was paused (don't accept user's ether submits)
/// event StakingPaused()
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StakingPaused {
}
/// StakingResumed - Staking was resumed (accept user's ether submits)
/// event StakingResumed()
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StakingResumed {
}
/// StakingLimitSet - Staking limit was set (rate limits user's submits)
/// event StakingLimitSet(uint256 maxStakeLimit, uint256 stakeLimitIncreasePerBlock)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StakingLimitSet {
    /// uint256
    #[prost(string, tag="1")]
    pub max_stake_limit: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="2")]
    pub stake_limit_increase_per_block: ::prost::alloc::string::String,
}
/// StakingLimitRemoved - Staking limit was removed
/// event StakingLimitRemoved()
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StakingLimitRemoved {
}
// ============================================
// EL/Withdrawal Events
// ============================================

/// ELRewardsReceived - The amount of ETH withdrawn from LidoExecutionLayerRewardsVault to Lido
/// event ELRewardsReceived(uint256 amount)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ElRewardsReceived {
    /// uint256
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
}
/// WithdrawalsReceived - The amount of ETH withdrawn from WithdrawalVault to Lido
/// event WithdrawalsReceived(uint256 amount)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawalsReceived {
    /// uint256
    #[prost(string, tag="1")]
    pub amount: ::prost::alloc::string::String,
}
// ============================================
// Locator Event
// ============================================

/// LidoLocatorSet - Lido locator set
/// event LidoLocatorSet(address lidoLocator)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LidoLocatorSet {
    #[prost(bytes="vec", tag="1")]
    pub lido_locator: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
