// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// Trader Joe V2 LBPair and LBFactory events
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Call metadata (only available on chains with DetailLevel: EXTENDED)
    #[prost(message, optional, tag="5")]
    pub call: ::core::option::Option<Call>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 20")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// LBPair events
        #[prost(message, tag="10")]
        Swap(super::Swap),
        #[prost(message, tag="11")]
        DepositedToBins(super::DepositedToBins),
        #[prost(message, tag="12")]
        WithdrawnFromBins(super::WithdrawnFromBins),
        #[prost(message, tag="13")]
        CompositionFees(super::CompositionFees),
        /// LBFactory events
        #[prost(message, tag="20")]
        LbPairCreated(super::LbPairCreated),
    }
}
/// Call metadata (only available on chains with DetailLevel: EXTENDED)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Call {
    #[prost(bytes="vec", tag="1")]
    pub caller: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub index: u32,
    #[prost(uint32, tag="3")]
    pub depth: u32,
    #[prost(enumeration="CallType", tag="4")]
    pub call_type: i32,
}
/// StorePool - minimal pool storage type
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorePool {
    /// tokenX address
    #[prost(bytes="vec", tag="1")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    /// tokenY address
    #[prost(bytes="vec", tag="2")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    /// factory address
    #[prost(bytes="vec", tag="3")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="4")]
    pub bin_step: u32,
}
/// key = <bytes lb_pair>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LbPairCreated {
    #[prost(bytes="vec", tag="1")]
    pub token_x: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub token_y: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="3")]
    pub bin_step: u32,
    /// address (STORE primary key)
    #[prost(bytes="vec", tag="4")]
    pub lb_pair: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="5")]
    pub pid: u32,
}
/// bytes32 packed amounts decoded into separate x/y uint128 values
/// Upper 128 bits = tokenX, Lower 128 bits = tokenY
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    #[prost(bytes="vec", tag="1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// active bin id
    #[prost(uint32, tag="3")]
    pub id: u32,
    /// uint128 (upper 128 bits of amountsIn)
    #[prost(string, tag="4")]
    pub amount_in_x: ::prost::alloc::string::String,
    /// uint128 (lower 128 bits of amountsIn)
    #[prost(string, tag="5")]
    pub amount_in_y: ::prost::alloc::string::String,
    /// uint128 (upper 128 bits of amountsOut)
    #[prost(string, tag="6")]
    pub amount_out_x: ::prost::alloc::string::String,
    /// uint128 (lower 128 bits of amountsOut)
    #[prost(string, tag="7")]
    pub amount_out_y: ::prost::alloc::string::String,
    #[prost(uint32, tag="8")]
    pub volatility_accumulator: u32,
    /// uint128 (upper 128 bits of totalFees)
    #[prost(string, tag="9")]
    pub total_fees_x: ::prost::alloc::string::String,
    /// uint128 (lower 128 bits of totalFees)
    #[prost(string, tag="10")]
    pub total_fees_y: ::prost::alloc::string::String,
    /// uint128 (upper 128 bits of protocolFees)
    #[prost(string, tag="11")]
    pub protocol_fees_x: ::prost::alloc::string::String,
    /// uint128 (lower 128 bits of protocolFees)
    #[prost(string, tag="12")]
    pub protocol_fees_y: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositedToBins {
    #[prost(bytes="vec", tag="1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="3")]
    pub ids: ::prost::alloc::vec::Vec<u64>,
    /// bytes32\[\] (each packed uint128 x | uint128 y)
    #[prost(bytes="vec", repeated, tag="4")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WithdrawnFromBins {
    #[prost(bytes="vec", tag="1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, repeated, tag="3")]
    pub ids: ::prost::alloc::vec::Vec<u64>,
    /// bytes32\[\] (each packed uint128 x | uint128 y)
    #[prost(bytes="vec", repeated, tag="4")]
    pub amounts: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompositionFees {
    #[prost(bytes="vec", tag="1")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag="2")]
    pub id: u32,
    /// uint128
    #[prost(string, tag="3")]
    pub total_fees_x: ::prost::alloc::string::String,
    /// uint128
    #[prost(string, tag="4")]
    pub total_fees_y: ::prost::alloc::string::String,
    /// uint128
    #[prost(string, tag="5")]
    pub protocol_fees_x: ::prost::alloc::string::String,
    /// uint128
    #[prost(string, tag="6")]
    pub protocol_fees_y: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    Unspecified = 0,
    Call = 1,
    Callcode = 2,
    Delegate = 3,
    Static = 4,
    Create = 5,
}
impl CallType {
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallType::Unspecified => "CALL_TYPE_UNSPECIFIED",
            CallType::Call => "CALL_TYPE_CALL",
            CallType::Callcode => "CALL_TYPE_CALLCODE",
            CallType::Delegate => "CALL_TYPE_DELEGATE",
            CallType::Static => "CALL_TYPE_STATIC",
            CallType::Create => "CALL_TYPE_CREATE",
        }
    }
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TYPE_CALL" => Some(Self::Call),
            "CALL_TYPE_CALLCODE" => Some(Self::Callcode),
            "CALL_TYPE_DELEGATE" => Some(Self::Delegate),
            "CALL_TYPE_STATIC" => Some(Self::Static),
            "CALL_TYPE_CREATE" => Some(Self::Create),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
