// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// <https://github.com/Uniswap/v4-core/blob/main/src/interfaces/IPoolManager.sol>
/// <https://github.com/Uniswap/v4-core/blob/59d3ecf53afa9264a16bba0e38f4c5d2231f80bc/src/interfaces/IProtocolFees.sol>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// IPoolManager
        #[prost(message, tag="10")]
        Swap(super::Swap),
        #[prost(message, tag="11")]
        Initialize(super::Initialize),
        #[prost(message, tag="12")]
        ModifyLiquidity(super::ModifyLiquidity),
        #[prost(message, tag="13")]
        Donate(super::Donate),
        /// IProtocolFees
        #[prost(message, tag="14")]
        ProtocolFeeControllerUpdated(super::ProtocolFeeControllerUpdated),
        #[prost(message, tag="15")]
        ProtocolFeeUpdated(super::ProtocolFeeUpdated),
    }
}
/// / @notice Emitted when a new pool is initialized
/// / @param id The abi encoded hash of the pool key struct for the new pool
/// / @param currency0 The first currency of the pool by address sort order
/// / @param currency1 The second currency of the pool by address sort order
/// / @param fee The fee collected upon every swap in the pool, denominated in
/// / hundredths of a bip
/// / @param tickSpacing The minimum number of ticks between initialized ticks
/// / @param hooks The hooks contract address for the pool, or address(0) if none
/// / @param sqrtPriceX96 The price of the pool on initialization
/// / @param tick The initial tick of the pool corresponding to the initialized
/// / price
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Initialize {
    /// STORE primary key
    ///
    /// address (Pool ID)
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// address (token0)
    #[prost(bytes="vec", tag="2")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    /// address (token1)
    #[prost(bytes="vec", tag="3")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    /// uint24 (e.g., 3000 represents 0.30%)
    #[prost(uint64, tag="4")]
    pub fee: u64,
    /// int24 (e.g., 60)
    #[prost(int32, tag="5")]
    pub tick_spacing: i32,
    /// NOT IMPLEMENTED
    #[prost(string, optional, tag="6")]
    pub hooks: ::core::option::Option<::prost::alloc::string::String>,
    /// uint160
    #[prost(string, tag="7")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    /// int24
    #[prost(int32, tag="8")]
    pub tick: i32,
}
/// StorePool - minimal pool storage type
/// Primary key: pool id
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorePool {
    /// token0 address
    #[prost(bytes="vec", tag="1")]
    pub currency0: ::prost::alloc::vec::Vec<u8>,
    /// token1 address
    #[prost(bytes="vec", tag="2")]
    pub currency1: ::prost::alloc::vec::Vec<u8>,
    /// factory address that initialized the pool
    #[prost(bytes="vec", tag="3")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Emitted for swaps between currency0 and currency1
/// / @param id The abi encoded hash of the pool key struct for the pool that was
/// / modified
/// / @param sender The address that initiated the swap call, and that received
/// / the callback
/// / @param amount0 The delta of the currency0 balance of the pool
/// / @param amount1 The delta of the currency1 balance of the pool
/// / @param sqrtPriceX96 The sqrt(price) of the pool after the swap, as a Q64.96
/// / @param liquidity The liquidity of the pool after the swap
/// / @param tick The log base 1.0001 of the price of the pool after the swap
/// / @param fee The swap fee in hundredths of a bip
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Swap {
    /// address (Pool ID)
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// int256
    #[prost(string, tag="3")]
    pub amount0: ::prost::alloc::string::String,
    /// int256
    #[prost(string, tag="4")]
    pub amount1: ::prost::alloc::string::String,
    /// uint160
    #[prost(string, tag="5")]
    pub sqrt_price_x96: ::prost::alloc::string::String,
    /// uint128
    #[prost(string, tag="6")]
    pub liquidity: ::prost::alloc::string::String,
    /// int24
    #[prost(int32, tag="7")]
    pub tick: i32,
    /// int256
    #[prost(string, tag="8")]
    pub fee: ::prost::alloc::string::String,
}
/// / @notice Emitted when a liquidity position is modified
/// / @param id The abi encoded hash of the pool key struct for the pool that was
/// / modified
/// / @param sender The address that modified the pool
/// / @param tickLower The lower tick of the position
/// / @param tickUpper The upper tick of the position
/// / @param liquidityDelta The amount of liquidity that was added or removed
/// / @param salt The extra data to make positions unique
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModifyLiquidity {
    /// address (Pool ID)
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// int24
    #[prost(int32, tag="3")]
    pub tick_lower: i32,
    /// int24
    #[prost(int32, tag="4")]
    pub tick_upper: i32,
    /// int128
    #[prost(string, tag="5")]
    pub liquidity_delta: ::prost::alloc::string::String,
    /// bytes32
    #[prost(bytes="vec", tag="6")]
    pub salt: ::prost::alloc::vec::Vec<u8>,
}
/// / @notice Emitted for donations
/// / @param id The abi encoded hash of the pool key struct for the pool that was
/// / donated to
/// / @param sender The address that initiated the donate call
/// / @param amount0 The amount donated in currency0
/// / @param amount1 The amount donated in currency1
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Donate {
    /// address (Pool ID)
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// address
    #[prost(bytes="vec", tag="2")]
    pub sender: ::prost::alloc::vec::Vec<u8>,
    /// uint256
    #[prost(string, tag="3")]
    pub amount0: ::prost::alloc::string::String,
    /// uint256
    #[prost(string, tag="4")]
    pub amount1: ::prost::alloc::string::String,
}
/// / @notice Emitted when the protocol fee controller address is updated in
/// / setProtocolFeeController.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolFeeControllerUpdated {
    /// address
    #[prost(bytes="vec", tag="1")]
    pub protocol_fee_controller: ::prost::alloc::vec::Vec<u8>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProtocolFeeUpdated {
    /// address (Pool ID)
    #[prost(bytes="vec", tag="1")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    /// uint24
    #[prost(uint64, tag="2")]
    pub protocol_fee: u64,
}
// @@protoc_insertion_point(module)
