// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Events {
    #[prost(message, repeated, tag="1")]
    pub transactions: ::prost::alloc::vec::Vec<Transaction>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transaction {
    #[prost(bytes="vec", tag="1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", optional, tag="3")]
    pub to: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    /// uint256
    #[prost(string, tag="6")]
    pub gas_price: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub gas_limit: u64,
    #[prost(uint64, tag="8")]
    pub gas_used: u64,
    /// uint256
    #[prost(string, tag="9")]
    pub value: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="10")]
    pub logs: ::prost::alloc::vec::Vec<Log>,
}
/// <https://github.com/Uniswap/v1-contracts/blob/master/contracts/uniswap_exchange.vy>
/// <https://github.com/Uniswap/v1-contracts/blob/master/contracts/uniswap_factory.vy>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Log {
    #[prost(bytes="vec", tag="1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag="2")]
    pub ordinal: u64,
    #[prost(bytes="vec", repeated, tag="3")]
    pub topics: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes="vec", tag="4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof="log::Log", tags="10, 11, 12, 13, 14, 15, 16")]
    pub log: ::core::option::Option<log::Log>,
}
/// Nested message and enum types in `Log`.
pub mod log {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Log {
        /// Exchange
        #[prost(message, tag="10")]
        TokenPurchase(super::TokenPurchase),
        #[prost(message, tag="11")]
        EthPurchase(super::EthPurchase),
        #[prost(message, tag="12")]
        AddLiquidity(super::AddLiquidity),
        #[prost(message, tag="13")]
        RemoveLiquidity(super::RemoveLiquidity),
        #[prost(message, tag="14")]
        Transfer(super::Transfer),
        #[prost(message, tag="15")]
        Approval(super::Approval),
        /// Factory
        #[prost(message, tag="16")]
        NewExchange(super::NewExchange),
    }
}
/// / @notice Emitted when ETH is sold for tokens
/// / @param buyer The address of the buyer
/// / @param eth_sold The amount of ETH sold
/// / @param tokens_bought The amount of tokens bought
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenPurchase {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (indexed)
    #[prost(string, tag="2")]
    pub eth_sold: ::prost::alloc::string::String,
    /// uint256 (indexed)
    #[prost(string, tag="3")]
    pub tokens_bought: ::prost::alloc::string::String,
}
/// / @notice Emitted when tokens are sold for ETH
/// / @param buyer The address of the buyer
/// / @param tokens_sold The amount of tokens sold
/// / @param eth_bought The amount of ETH bought
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EthPurchase {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub buyer: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (indexed)
    #[prost(string, tag="2")]
    pub tokens_sold: ::prost::alloc::string::String,
    /// uint256 (indexed)
    #[prost(string, tag="3")]
    pub eth_bought: ::prost::alloc::string::String,
}
/// / @notice Emitted when liquidity is added to the pool
/// / @param provider The liquidity provider address
/// / @param eth_amount The amount of ETH added
/// / @param token_amount The amount of tokens added
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddLiquidity {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (indexed)
    #[prost(string, tag="2")]
    pub eth_amount: ::prost::alloc::string::String,
    /// uint256 (indexed)
    #[prost(string, tag="3")]
    pub token_amount: ::prost::alloc::string::String,
}
/// / @notice Emitted when liquidity is removed from the pool
/// / @param provider The liquidity provider address
/// / @param eth_amount The amount of ETH removed
/// / @param token_amount The amount of tokens removed
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveLiquidity {
    /// address (indexed)
    #[prost(bytes="vec", tag="1")]
    pub provider: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (indexed)
    #[prost(string, tag="2")]
    pub eth_amount: ::prost::alloc::string::String,
    /// uint256 (indexed)
    #[prost(string, tag="3")]
    pub token_amount: ::prost::alloc::string::String,
}
/// / @notice Emitted when tokens are transferred
/// / @param from The address sending tokens
/// / @param to The address receiving tokens
/// / @param value The amount of tokens transferred
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfer {
    /// address (indexed as _from)
    #[prost(bytes="vec", tag="1")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed as _to)
    #[prost(bytes="vec", tag="2")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (_value)
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// / @notice Emitted when an approval is made
/// / @param owner The address of the token owner
/// / @param spender The address of the spender
/// / @param value The amount of tokens approved
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Approval {
    /// address (indexed as _owner)
    #[prost(bytes="vec", tag="1")]
    pub owner: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed as _spender)
    #[prost(bytes="vec", tag="2")]
    pub spender: ::prost::alloc::vec::Vec<u8>,
    /// uint256 (_value)
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
}
/// / @notice Emitted when a new exchange is created
/// / @param token The token address
/// / @param exchange The exchange address
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NewExchange {
    /// log.address - the factory that created the exchange
    #[prost(bytes="vec", tag="1")]
    pub factory: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="2")]
    pub token: ::prost::alloc::vec::Vec<u8>,
    /// address (indexed)
    #[prost(bytes="vec", tag="3")]
    pub exchange: ::prost::alloc::vec::Vec<u8>,
}
// @@protoc_insertion_point(module)
