// @generated
// This file is @generated by prost-build.
/// Changed-key projection, not a complete bootstrap of every holder.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockBalances {
    #[prost(uint64, tag = "1")]
    pub number: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "4")]
    pub timestamp: u64,
    #[prost(message, repeated, tag = "5")]
    pub balances: ::prost::alloc::vec::Vec<Balance>,
    #[prost(message, repeated, tag = "6")]
    pub unresolved_wbnb_slots: ::prost::alloc::vec::Vec<UnresolvedSlot>,
    #[prost(uint64, tag = "7")]
    pub preimage_count: u64,
    #[prost(uint64, tag = "8")]
    pub wbnb_storage_changes: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Balance {
    /// ERC-20 contract; diagnostic format, not the public Events API
    #[prost(bytes = "vec", tag = "1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    /// before the first persisted change in this block
    #[prost(string, tag = "3")]
    pub old_amount: ::prost::alloc::string::String,
    /// after the last persisted change in this block
    #[prost(string, tag = "4")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnresolvedSlot {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub new_value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub ordinal: u64,
}
/// Discovery output only. A mapping-shaped storage write is NOT yet a balance.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageCandidates {
    #[prost(uint64, tag = "1")]
    pub number: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub parent_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "4")]
    pub candidates: ::prost::alloc::vec::Vec<MappingCandidate>,
    #[prost(message, repeated, tag = "5")]
    pub tokens: ::prost::alloc::vec::Vec<TokenActivity>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MappingCandidate {
    #[prost(bytes = "vec", tag = "1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub mapping_slot: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub storage_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub old_amount: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub ordinal: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenActivity {
    #[prost(bytes = "vec", tag = "1")]
    pub contract: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub transfer_holders: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint64, tag = "3")]
    pub storage_changes: u64,
    #[prost(uint64, tag = "4")]
    pub unclassified_storage_changes: u64,
    #[prost(bool, tag = "5")]
    pub code_changed: bool,
}
// @@protoc_insertion_point(module)
